// Generated by CoffeeScript 1.3.3
(function() {
  var Db, Server, db, mongodb, process_attempt, read_attempts;

  mongodb = require('mongodb');

  Db = mongodb.Db;

  Server = mongodb.Server;

  db = new Db('wbDB', new Server('localhost', 27017), {
    native_parser: true,
    w: -1,
    safe: false,
    disableDriverBSONSizeCheck: true
  });

  process_attempt = function(attempt, call_back) {
    return call_back(attempt.user);
  };

  read_attempts = function(call_back) {
    return db.open(function(err, db) {
      var collection;
      if (err) {
        return call_back(err);
      } else {
        collection = db.collection('attempts');
        return collection.find({
          "mp_id": "1",
          "user": {
            $type: 2
          }
        }, {
          limit: 1,
          skip: 1
        }, function(err, cursor) {
          if (err) {
            return call_back(err);
          } else {
            return cursor.toArray(function(err, attempts) {
              if (err) {
                return call_back(err);
              } else {
                return attempts.forEach(function(attempt) {
                  return process_attempt(attempt, call_back);
                });
              }
            });
          }
        });
      }
    });
  };

  read_attempts(function(msg) {
    console.log(msg);
    return db.close();
  });

}).call(this);
