// Generated by CoffeeScript 1.3.3
(function() {

  module.exports = {
    aws_key_id: 'AKIAI4RGCVMXUDD3CCXA',
    aws_key_secret: '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',
    aws_ssh_key_file: 'test.pem',
    aws_region: 'us-west-2',
    aws_user: 'ubuntu',
    aws_ami_name: 'ami-a0f27c90',
    aws_key_name: 'test',
    aws_security_group: 'quick-start-1',
    aws_instance_type: 't1.micro',
    aws_daemon_running_port: 8081,
    app_log_file_path: './wbServer.log',
    aws_log_file_path: './aws.log',
    port: 80,
    look_port: 8099,
    db_address: 'localhost',
    db_port: 27017,
    db_name: 'wbDB',
    db_collection_auth_name: 'users',
    db_collection_attempt_name: 'attempts'
  };

}).call(this);
