// Generated by CoffeeScript 1.3.3
(function() {
  var coursera_grade_api_key, cousera_grade_address;

  cousera_grade_address = 'https://class.coursera.org/hetero-2012-001/assignment/api/update_score';

  coursera_grade_api_key = '';

}).call(this);
