// Generated by CoffeeScript 1.3.3
(function() {
  var Logger, config, logger, ring_buffer;

  Logger = require('bunyan');

  config = require('./config');

  ring_buffer = new Logger.RingBuffer({
    limit: 200
  });

  logger = new Logger({
    name: 'wbServer',
    streams: [
      {
        stream: process.stdout,
        level: 'debug'
      }, {
        path: config.app_log_file_path,
        level: 'trace'
      }, {
        type: 'raw',
        stream: ring_buffer,
        level: 'trace'
      }
    ],
    serializers: {
      req: Logger.stdSerializers.req,
      res: Logger.stdSerializers.res
    }
  });

  exports.log = logger;

}).call(this);
