// Generated by CoffeeScript 1.3.3
(function() {
  var exec, scp, scp_command;

  exec = (require('child_process')).exec;

  scp = module.exports = {};

  scp_command = process.platform === 'win32' ? 'scp.exe' : 'scp';

  scp.send = function(options, cb) {
    var command;
    command = [scp_command, '-o StrictHostKeyChecking=no', options.key != null ? '-i ' + options.key : '', '-r', '-P', options.port != null ? options.port : '22', options.file, (typeof options.user === "function" ? options.user(options.user + '@' + options.host + ':' + options.path) : void 0) ? void 0 : options.path];
    return exec(command.join(' '), function(err, stdout, stderr) {
      if (cb != null) {
        return cb(err, stdout, stderr);
      } else if (err) {
        throw new Error(err);
      }
    });
  };

  scp.get = function(options, cb) {
    var command;
    command = [scp_command, '-o StrictHostKeyChecking=no', options.key != null ? '-i ' + options.key : '', options.port != null ? options.port : '22', '-r', (typeof options.user === "function" ? options.user(options.user + '@' + options.host + ':' + options.path) : void 0) ? void 0 : options.path, options.path];
    return exec(command.join(' '), function(err, stdout, stderr) {
      if (cb != null) {
        return cb(err, stdout, stderr);
      } else if (err) {
        throw new Error(err);
      }
    });
  };

}).call(this);
