// Generated by CoffeeScript 1.3.3
(function() {
  var exec, ssh, ssh_command;

  exec = (require('child_process')).exec;

  ssh = module.exports = {};

  ssh_command = process.platform === 'win32' ? 'ssh.exe' : 'ssh';

  ssh.exec = function(cmd, options, cb) {
    var command;
    command = [ssh_command, '-o StrictHostKeyChecking=no', options.key != null ? '-i ' + options.key : '', '-p', options.port != null ? options.port : '22', options.file, (typeof options.user === "function" ? options.user(options.user + '@' + options.host + ':' + options.path) : void 0) ? void 0 : options.path, "'" + cmd + "'"];
    return exec(command.join(' '), function(err, stdout, stderr) {
      if (cb != null) {
        return cb(err, stdout, stderr);
      } else if (err) {
        throw new Error(err);
      }
    });
  };

}).call(this);
