// Generated by CoffeeScript 1.3.3
(function() {
  var broadcast, config, register, request, url;

  url = require('url');

  request = require('request');

  config = require('./config');

  register = function(address) {
    var uri;
    uri = url.format({
      protocol: 'http:',
      hostname: config.master_address,
      port: config.master_port,
      pathname: '/is_registered'
    });
    return request({
      uri: uri,
      method: 'GET',
      json: true,
      body: {
        address: address.address
      }
    }, function(err, res, json) {
      if (err || ((json != null) && json.is_registered === false)) {
        return broadcast(address);
      }
    });
  };

  broadcast = function(address) {
    var body, uri;
    uri = url.format({
      protocol: 'http:',
      hostname: config.master_address,
      port: config.master_port,
      pathname: config.master_path
    });
    body = JSON.stringify({
      "address": address.address,
      "port": address.port,
      "max_processes": config.max_processes
    });
    return request({
      uri: uri,
      method: 'POST',
      json: true,
      body: body
    }, function() {
      return {};
    });
  };

  module.exports = {
    broadcast: broadcast,
    register: register
  };

}).call(this);
