// Generated by CoffeeScript 1.3.3
(function() {
  var async, clear_tmp, fs, stop, temp;

  fs = require('fs.extra');

  temp = require('temp');

  async = require('async');

  stop = function(params) {
    return process.exit(1);
  };

  clear_tmp = function(params, call_back) {
    var dir;
    temp.cleanup();
    dir = temp.dir;
    return fs.readdir(dir, function(err, files) {
      if (err) {
        return call_back(err, params);
      } else {
        return async(files, function(file) {
          if ((file.indexOf(config.tmpdir_prefix)) !== -1) {
            return fs.rmRecursive(file);
          }
        }, function() {
          return call_back(null, params);
        });
      }
    });
  };

  module.exports = {
    stop: stop,
    clear_tmp: clear_tmp
  };

}).call(this);
